apiVersion: v1
kind: Service
metadata:
  name: teamspeak-tcp
  namespace: apps-teamspeak
  labels:
    app: teamspeak
    release: apps-teamspeak
  annotations:
    meta.helm.sh/release-name: apps-teamspeak
    meta.helm.sh/release-namespace: teamspeak
    metallb.universe.tf/allow-shared-ip: "teamspeak"
spec:
  ports:
    - name: teamspeak-filetransfer
      protocol: TCP
      port: 30033
      targetPort: 30033
    - name: teamspeak-serverquery
      protocol: TCP
      port: 10011
      targetPort: 10011
  selector:
    app: teamspeak
    release: apps-teamspeak
  type: LoadBalancer
