apiVersion: v1
kind: Namespace
metadata:
  name: apps-teamspeak

---

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-teamspeak
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./flux/apps/common/teamspeak/test
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg

# ---

# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: apps-teamspeak-db
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   path: ./flux/apps/common/teamspeak/db
#   prune: true
#   decryption:
#     provider: sops
#     secretRef:
#       name: sops-gpg
